### ISSUE TITLE
20-21桁目が英字の場合が動作しないです。

### ISSUE THREAD

**Issue by sinh927** [rapidreport/barcode-java#1]
以下の日本郵便の手順に従った場合、
http://www.post.japanpost.jp/zipcode/zipmanual/p20.html
20-21桁目が英字の場合には、制御コードを残す必要があります。

ですが、現状のロジックでは、最後の英字が切り捨てられています。

**Comment by shuetsu** [comment]
こんにちは。報告ありがとうございます。

制御コードを残すように修正し、タグ1.3を作成しました。
